global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'algo-trade-monitor'



scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Algo Trading Application
  - job_name: 'algo-trade-app'
    static_configs:
      - targets: ['algo-trade-app:8001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # TimescaleDB PostgreSQL Exporter (requires postgres_exporter)
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # cAdvisor for container metrics (optional - commented out for storage optimization)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   scrape_interval: 30s
  #   metrics_path: '/metrics'

# Storage optimization - these settings are now command line arguments
# retention_time: 7d
# retention_size: 2GB